"""Pydantic Conditionals: JSON Schema conditional validation for Pydantic models.

Provides a fluent API to add ``if``/``then``/``else`` conditional rules
and ``dependentSchemas`` to the JSON Schema generated by Pydantic models.

Typical usage::
    from pydantic_conditionals import ConditionalModel, when, when_present

    class Address(ConditionalModel, BaseModel):
        country: str
        postal_code: str

        model_conditions: ClassVar = (
            when(country="USA").require("postal_code"),
            when_present("credit_card").require("billing_address"),
        )
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel

from .conditional import (
    ConditionalModel,
    DependentSchemaBuilder,
    QueryBuilder,
    RequiredWith,
)

__all__ = ["ConditionalModel", "RequiredWith", "when", "when_present", "when_schema"]


def when(**kwargs: Any) -> QueryBuilder:
    """Create a conditional validation rule triggered by field values.

    Each keyword argument specifies a field name and the value it must
    match for the rule to activate.

    Args:
        **kwargs: Field-value pairs that form the ``if`` condition.

    Returns:
        A :class:`QueryBuilder` for defining the rule's constraints.

    Example::
        when(country="USA").require("postal_code").constrain(
            postal_code=Field(pattern=r"^\\d{5}$")
        )
    """
    return QueryBuilder(kwargs)


def when_schema(schema: type[BaseModel]) -> QueryBuilder:
    return QueryBuilder.from_schema(schema)


def when_present(field: str) -> DependentSchemaBuilder:
    """Create a ``dependentSchemas`` rule triggered by a field's presence.

    Unlike :func:`when`, this does not check the field's *value* - only
    whether the field is present in the input.

    Args:
        field: The trigger field name.

    Returns:
        A :class:`DependentSchemaBuilder` for defining the dependent schema.

    Example::
        when_present("credit_card").require("billing_address")
    """
    return DependentSchemaBuilder(field)
